$p=$(pwd).Path; docker run -it -v "${p}/.ssh:/root/.ssh" -v "${p}:/workdir" --workdir "/workdir" --rm microsoft/ansible:latest ansible-playbook --become -e "ansible_python_interpreter=/usr/bin/python3" -u ubuntu -i 178.154.231.119, --extra-vars "hostname=vmmaster" stdprep.yml

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [178.154.231.119]

TASK [Set hostname] ****************************************************************************************************
changed: [178.154.231.119]

TASK [Set timezone] ****************************************************************************************************
changed: [178.154.231.119]

TASK [copy ddnsclient config] ******************************************************************************************
changed: [178.154.231.119]

TASK [copy ddnsclient for daemon] **************************************************************************************
changed: [178.154.231.119]

TASK [replace HOSTNAME] ************************************************************************************************
changed: [178.154.231.119]

TASK [install dynamic dns client] **************************************************************************************
changed: [178.154.231.119]

TASK [register service] ************************************************************************************************
changed: [178.154.231.119]

TASK [install fail2ban package] ****************************************************************************************
changed: [178.154.231.119]

TASK [copy fail2ban local config] **************************************************************************************
changed: [178.154.231.119]

TASK [Update and upgrade apt packages] *********************************************************************************
fatal: [178.154.231.119]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to 178.154.231.119 closed.\r\n", "unreachable": true}
        to retry, use: --limit @/workdir/stdprep.retry

PLAY RECAP *************************************************************************************************************
178.154.231.119            : ok=10   changed=9    unreachable=1    failed=0



$p=$(pwd).Path; docker run -it -v "${p}/.ssh:/root/.ssh" -v "${p}:/workdir" --workdir "/workdir" --rm microsoft/ansible:latest ansible-playbook --become -e "ansible_python_interpreter=/usr/bin/python3" -u ubuntu -i 178.154.231.119, --extra-vars "hostname=vmmaster" stdprep.yml

PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [178.154.231.119]

TASK [Set hostname] ****************************************************************************************************
changed: [178.154.231.119]

TASK [Set timezone] ****************************************************************************************************
ok: [178.154.231.119]

TASK [copy ddnsclient config] ******************************************************************************************
changed: [178.154.231.119]

TASK [copy ddnsclient for daemon] **************************************************************************************
ok: [178.154.231.119]

TASK [replace HOSTNAME] ************************************************************************************************
changed: [178.154.231.119]

TASK [install dynamic dns client] **************************************************************************************
ok: [178.154.231.119]

TASK [register service] ************************************************************************************************
changed: [178.154.231.119]

TASK [install fail2ban package] ****************************************************************************************
ok: [178.154.231.119]

TASK [copy fail2ban local config] **************************************************************************************
ok: [178.154.231.119]

TASK [Update and upgrade apt packages] *********************************************************************************
 [WARNING]: Could not find aptitude. Using apt-get instead.

ok: [178.154.231.119]

TASK [Completed] *******************************************************************************************************
ok: [178.154.231.119] => {
    "msg": "Completed"
}

PLAY RECAP *************************************************************************************************************
178.154.231.119            : ok=12   changed=4    unreachable=0    failed=0




$p=$(pwd).Path; docker run -it -v "${p}/.ssh:/root/.ssh" -v "${p}:/workdir" --workdir "/workdir" --rm microsoft/ansible:latest ansible-playbook --become -e "ansible_python_interpreter=/usr/bin/python3" -u ubuntu -i 178.154.231.119, --extra-vars "hostname=vmmaster" k8s.yml | Tee-Object ansible_k8s.log

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [178.154.231.119]

TASK [copy install script] *****************************************************
changed: [178.154.231.119]

TASK [install packages] ********************************************************
changed: [178.154.231.119]

PLAY RECAP *********************************************************************
178.154.231.119            : ok=3    changed=2    unreachable=0    failed=0

